<a href="https://colab.research.google.com/github/PhanDuyNhat/AI/blob/Code_AI/week8(studying%20process).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artifical Neural Network

In [2]:
from sklearn.linear_model import Perceptron

x = [[0,0],[0,1],[1,0],[1,1]]
t = [0,1,1,1]

model = Perceptron()
model.fit(x,t)
# model.score(x,t)

x1 = [[0.5,0.5],[0.5,0],[0,0.5],[0.4,0]]
y1 = model.predict(x1)
print(y1)
model.score(x1,y1)


[1 0 0 0]


1.0

In [3]:

from os.path import split
from sklearn.linear_model import Perceptron
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler



In [19]:

iris = datasets.load_iris()
x = iris.data
y = iris.target
print(x[:5])#hien thi ra 5 dong dau tien
print(y[:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0]


In [32]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.3) # lay ti le 70 /30 
sc = StandardScaler()
sc.fit(x_train)
x_train_std = sc.transform(x_train)
x_test_std = sc.transform(x_test)
print(x_train_std[:5], x_train[:5])
print(y[:5])

[[ 1.569077   -0.2071311   1.30617423  1.26940114]
 [ 1.68986372  0.2322379   1.36242865  0.87583681]
 [-0.36351051 -1.52523812  0.12483125 -0.04247996]
 [ 0.60278325 -1.30555362  0.74362995  0.48227248]
 [ 0.9651434  -0.2071311   0.46235782  0.35108437]] [[7.1 3.  5.9 2.1]
 [7.2 3.2 6.  1.8]
 [5.5 2.4 3.8 1.1]
 [6.3 2.5 4.9 1.5]
 [6.6 3.  4.4 1.4]]
[0 0 0 0 0]


In [33]:
model = Perceptron(max_iter=1000000, eta0=0.2,random_state=0)
 #maxinter : so lan hoc
 #eta0 : toc do hoc 
 #randomstate : gia tri ngau nhien cua he thong
model.fit(x_train,y_train)
y_pred = model.predict(x_test_std)
print(y_pred)
print(y_test)
print("Độ chính xác của mô hình: ", accuracy_score(y_test,y_pred))

[1 2 2 2 2 2 2 1 2 0 2 1 2 2 2 2 2 0 2 1 0 0 2 2 1 1 2 2 2 2 2 2 2 2 0 1 2
 2 2 1 1 2 0 1 1]
[1 2 1 2 1 1 2 1 2 0 1 0 2 2 2 1 2 0 2 1 0 0 1 2 1 1 1 1 2 2 2 2 2 1 0 1 2
 2 2 0 1 1 0 0 0]
Độ chính xác của mô hình:  0.6888888888888889


In [34]:
model = Perceptron(max_iter=1000000, eta0=0.2,random_state=0) #maxinter : so lan hoc, eta0 : toc do hoc, randomstate : gia tri ngau nhien cua he thong
model.fit(x_train_std,y_train)
y_pred = model.predict(x_test_std)
print(y_pred)
print(y_test)
print("Độ chính xác của mô hình: ", accuracy_score(y_test,y_pred))

[1 1 2 2 1 1 2 1 2 0 2 0 1 1 1 1 2 0 2 1 0 0 1 2 1 1 1 1 2 2 2 2 2 1 0 1 2
 2 2 0 1 1 0 0 0]
[1 2 1 2 1 1 2 1 2 0 1 0 2 2 2 1 2 0 2 1 0 0 1 2 1 1 1 1 2 2 2 2 2 1 0 1 2
 2 2 0 1 1 0 0 0]
Độ chính xác của mô hình:  0.8666666666666667


# CRABS

In [57]:
import numpy as np
from sklearn.linear_model import Perceptron
#Chua data, co thu vien chuan hoa lan, chu, so viet tay, cac vat dung trong nha
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
#Scale data de cho deu nhau (Ex:0, 1000 000 --> 0,1)
from sklearn.preprocessing import StandardScaler

import pandas as pd
url = 'crabs.csv'
data = pd.read_csv(url)

dataframe=data.replace(['F','M','B','O'],[0,1,1,0])
print(dataframe)


     speies  sex  index  fontallip  rearwidth  length  width  depth
0         1    1      1        8.1        6.7    16.1   19.0    7.0
1         1    1      2        8.8        7.7    18.1   20.8    7.4
2         1    1      3        9.2        7.8    19.0   22.4    7.7
3         1    1      4        9.6        7.9    20.1   23.1    8.2
4         1    1      5        9.8        8.0    20.3   23.0    8.2
..      ...  ...    ...        ...        ...     ...    ...    ...
195       0    0     46       21.4       18.0    41.2   46.2   18.7
196       0    0     47       21.7       17.1    41.7   47.2   19.6
197       0    0     48       21.9       17.2    42.6   47.4   19.5
198       0    0     49       22.5       17.2    43.0   48.7   19.8
199       0    0     50       23.1       20.2    46.2   52.5   21.1

[200 rows x 8 columns]


In [59]:
x =dataframe.drop('speies', axis = 1)
y =dataframe.speies
print(x[:])
print(y[:])

     sex  index  fontallip  rearwidth  length  width  depth
0      1      1        8.1        6.7    16.1   19.0    7.0
1      1      2        8.8        7.7    18.1   20.8    7.4
2      1      3        9.2        7.8    19.0   22.4    7.7
3      1      4        9.6        7.9    20.1   23.1    8.2
4      1      5        9.8        8.0    20.3   23.0    8.2
..   ...    ...        ...        ...     ...    ...    ...
195    0     46       21.4       18.0    41.2   46.2   18.7
196    0     47       21.7       17.1    41.7   47.2   19.6
197    0     48       21.9       17.2    42.6   47.4   19.5
198    0     49       22.5       17.2    43.0   48.7   19.8
199    0     50       23.1       20.2    46.2   52.5   21.1

[200 rows x 7 columns]
0      1
1      1
2      1
3      1
4      1
      ..
195    0
196    0
197    0
198    0
199    0
Name: speies, Length: 200, dtype: int64


In [60]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.3)
sc = StandardScaler()
sc.fit(x_train)
x_train_std = sc.transform(x_train)
x_test_std = sc.transform(x_test)
print(x_train_std[:])
print(y.T)

[[ 9.85814884e-01  1.18396703e+00  7.15534326e-01  5.85899255e-01
   1.11445767e+00  1.08235300e+00  8.63422872e-01]
 [ 9.85814884e-01 -9.25399515e-01 -8.90643992e-01 -6.64957749e-01
  -6.00396538e-01 -5.35487391e-01 -8.35855880e-01]
 [-1.01438923e+00 -1.12953176e+00 -2.98894085e-01 -1.34291142e-01
  -4.89760782e-01 -5.10597538e-01 -3.75034524e-01]
 [-1.01438923e+00 -5.17135023e-01 -9.75179693e-01 -4.37529203e-01
  -7.80179641e-01 -7.22161282e-01 -8.35855880e-01]
 [-1.01438923e+00  2.99393961e-01  8.56427161e-01  1.19237538e+00
   6.71914651e-01  7.09005217e-01  7.48217533e-01]
 [ 9.85814884e-01 -1.76914613e-01  1.10701513e-02 -5.51243476e-01
  -1.99341924e-01 -2.86588869e-01 -8.70211758e-02]
 [ 9.85814884e-01 -5.85179105e-01 -6.93394023e-01 -5.89148234e-01
  -6.69543885e-01 -6.22601873e-01 -6.91849206e-01]
 [ 9.85814884e-01 -1.53779625e+00 -1.84871527e+00 -1.84000524e+00
  -1.87270773e+00 -1.87953941e+00 -1.84390260e+00]
 [-1.01438923e+00 -4.08264492e-02  6.30998625e-01  5.47994497e-0

In [52]:
model = Perceptron(max_iter = 200, eta0= 0.13 , random_state = 0) #so lan train, toc do hoc
model.fit(x_train_std, y_train)
y_pred = model.predict(x_test_std)
print(y_pred[:])
print(y_test[:].T)
print("Do chinh xac:", accuracy_score(y_test, y_pred))


[1 1 1 1 0 1 1 0 1 0 0 1 1 1 0 1 0 0 1 1 1 1 0 1 1 1 1 1 0 0 0 0 0 0 1 0 1
 0 0 0 0 1 0 0 0 1 1 1 1 0 0 1 0 1 1 0 0 0 1 1]
80     1
44     1
54     1
40     1
166    0
31     1
41     1
197    0
77     1
122    0
108    0
81     1
52     1
89     1
130    0
11     1
115    0
188    0
53     1
68     1
42     1
15     1
112    0
35     1
55     1
57     1
56     1
72     1
180    0
187    0
106    0
120    0
184    0
154    0
48     1
165    0
59     1
119    0
140    0
186    0
111    0
37     1
127    0
194    0
167    0
73     1
93     1
76     1
25     1
173    0
142    0
100    0
193    0
46     1
30     1
168    0
129    0
116    0
86     1
6      1
Name: speies, dtype: int64
Do chinh xac: 0.9833333333333333


In [64]:
x1 = [[0,50,23.1,20.2,46.2,52.2,21.1]]
y1 = model.predict(x1)
print(y1)
model.score(x1,y1)

[1]


1.0

# LUNG_CANCER



In [86]:
import numpy as np
from sklearn.linear_model import Perceptron
#Chua data, co thu vien chuan hoa lan, chu, so viet tay, cac vat dung trong nha
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
#Scale data de cho deu nhau (Ex:0, 1000 000 --> 0,1)
from sklearn.preprocessing import StandardScaler

import pandas as pd
url1 = 'lung_cancer_examples.csv'
data = pd.read_csv(url1)
dataframe=data.drop('Name', axis = 1) #xoa cot
dataframe1=dataframe.drop('Surname', axis = 1)
x=dataframe1.drop('Result', axis = 1)
y =data.Result
print(x)
print(y)



    Age  Smokes  AreaQ  Alkhol
0    35       3      5       4
1    27      20      2       5
2    30       0      5       2
3    28       0      8       1
4    68       4      5       6
5    34       0     10       0
6    58      15     10       0
7    22      12      5       2
8    45       2      6       0
9    52      18      4       5
10   33       4      8       0
11   18      10      6       3
12   25       2      5       1
13   28      20      2       8
14   34      25      4       8
15   39      18      8       1
16   42      22      3       5
17   19      12      8       0
18   62       5      4       3
19   73      10      7       6
20   55      15      1       3
21   33       8      8       1
22   22      20      6       2
23   44       5      8       1
24   77       3      2       6
25   21      20      5       3
26   37      15      6       2
27   34      12      8       0
28   55      20      1       4
29   40      20      2       7
30   36      13      5       2
31   56 

In [87]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.3)
sc = StandardScaler()
sc.fit(x_train)
x_train_std = sc.transform(x_train)
x_test_std = sc.transform(x_test)
print(x_train_std[:])
print(y[:])
model = Perceptron(max_iter = 200, eta0= 0.13 , random_state = 0) #so lan train, toc do hoc
model.fit(x_train_std, y_train)
y_pred = model.predict(x_test_std)
print(y_pred[:])
print(y_test[:].T)
print("Do chinh xac:", accuracy_score(y_test, y_pred))



[[ 1.13529655  0.81096463 -1.05702652  0.44830837]
 [ 2.07802381  0.15125134 -1.05702652  0.89661673]
 [-0.69123752  0.81096463 -1.49478498  2.24154184]
 [ 1.72450109  0.81096463 -0.1815096   0.44830837]
 [-0.04311253  0.54707931  1.13176577 -0.89661673]
 [-1.04476024  0.81096463  0.25624885 -0.44830837]
 [ 1.9601829  -0.50846195  0.69400731  1.3449251 ]
 [-0.3377148  -1.82788853  2.00728268 -1.3449251 ]
 [-0.86799888  0.81096463  1.13176577 -0.44830837]
 [ 2.19586472 -1.43206055 -1.49478498  1.3449251 ]
 [-1.2215216  -0.24457663  1.13176577 -1.3449251 ]
 [-1.10368069  0.81096463 -0.1815096   0.        ]
 [-1.10368069  0.81096463  1.13176577  0.        ]
 [-0.80907843 -0.50846195  0.69400731 -0.44830837]
 [-0.75015797  0.81096463 -1.49478498  0.89661673]
 [-0.04311253  0.15125134  0.69400731 -0.44830837]
 [-0.69123752 -1.82788853  1.13176577 -0.89661673]
 [ 0.25148974  2.13039121 -1.93254343  1.3449251 ]
 [-0.3377148  -0.24457663  1.13176577 -1.3449251 ]
 [-0.39663525 -0.77234727  1.13

In [96]:
x1 = [[35,3,5,4]]
y1 = model.predict(x1)
print(y1)


[1]
